Whitelist: []
Blacklist: []
LogRotationEnabled: true
EmailNotifications:
  sender: ""
  recipients: ["admin@example.com"]
  host: "smtp.gmail.com"
  port: 587
  username: "<your_email>"
  password: "<your_app_specific_password>"
